[build]
  command = "npm run build"
  publish = "/"
  base = "/"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "https://www.suncalc.org/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"